### ISSUE TITLE
Coveralls changed the API

### ISSUE THREAD

**Issue by florence** [rpless/cover-coveralls#6]
Coveralls seems to have change their API. They now want a "source_digest" (MD5 hash of the file) instead of the file itself.

**Comment by rpless** [comment]
This doesn't look terrible. Unless you've started, I can probably have this fix in within the hour.

**Comment by florence** [comment]
I haven't touched it, so if you would be so kind :)

**Comment by rpless** [comment]
Fixed in #9.
